config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  # get 'errors/not_found'
  # get 'errors/internal_server_error'
  
  resources :microposts
  resources :users do
    member do
      get :following, :followers
    end
  end 
  resources :relationships, only: [:create, :destroy] 
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get "/" => "microposts#index"
  get "sign_up" => "register#new"
  post "sign_up" => "register#create"

  get '/login',to: 'sessions#new'
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"


  match "/404", to: 'errors#not_found', via: :all
  match "/422", to: 'errors#unprocessable', via: :all
  match "/500", to: 'errors#internal_server_error', via: :all
  
  root 'users#index'
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  include SessionsHelper
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update] # Case (1)
  def new

  end

  def create
    @user = User.find_by(email: params[:a][:email])
    if @user #nếu tồn tại user
      @user.create_reset_digest   #tạo ra mã resetpassword -> lưu vào database
      @user.send_password_reset_email   #gửi mail cho user
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
        render 'edit'
    elsif @user.update(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render 'edit'
    end

  end
  private
      
    def user_params
        params.require(:user).permit(:password, :password_confirmation)
    end


    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirms a valid user.
    def valid_user
         unless (@user && @user.authenticated?(:reset, params[:id]))
                redirect_to root_url
          end
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
         flash[:danger] = "Password reset has expired."
         redirect_to new_password_reset_url
      end
    end
  
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
        <% provide(:title, 'Reset password') %>
        <div class="text-center">
             <h1>Reset password</h1>
        </div>
       
        <div class="row justify-content-center">
            <div class="col-md-6 col-md-offset-3">
                <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
                    <%= hidden_field_tag :email, @user.email %>
                    <%= f.label :password %>
                    <%= f.password_field :password, class: 'form-control' %>
                    <%= f.label :password_confirmation, "Confirmation" %>
                    <%= f.password_field :password_confirmation, class: 'form-control' %>
                   <div class="text-center"> 
                         <%= f.submit "Update password", class: "btn btn-primary my-5" %>
                   </div>
                <% end %>
            </div>
        </div>

app/views/password_resets/new.html.erb
     <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6 col-xl-5">
                        <div class="card overflow-hidden">
                            <div class="bg-soft-primary" style="background-color:rgba(85,110,230,.25)!important">
                                <div class="row">
                                    <div class="col-7">
                                        <div class="text-primary p-4">
                                            <h5 class="text-primary"> Reset Password</h5>
                                            
                                        </div>
                                    </div>
                                    <div class="col-5 align-self-end">
                                        <img src="assets\images\profile-img.png" alt="" class="img-fluid">
                                    </div>
                                </div>
                            </div>
                            <div class="card-body pt-0"> 
                                <div>
                                    <a href="index.html">
                                        <div class="avatar-md profile-user-wid mb-2">
                                            <span class="avatar-title rounded-circle bg-light">
                                                <img src="assets\images\logo.svg" alt="" class="rounded-circle" height="34">
                                            </span>
                                        </div>
                                    </a>
                                </div>
                                
                                <div class="p-2">
                                    <div class="alert alert-success text-center mb-4" role="alert">
                                        Enter your Email and instructions will be sent to you!
                                    </div>
                        
                                        <%= form_for(:a, url: password_resets_path) do |f| %>
                                             
                                            
                                              <div class="form-group">
                                                    <%= f.label :email %>
                                                    <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
                                                   
                                              </div>
                                              <div class="form-group row mb-0">
                                                <div class="col-12 text-right">
                                                    <button class="btn btn-primary w-md waves-effect waves-light" type="submit">Reset</button>
                                                </div>
                                              </div>
                                        <% end %>
                                   
                                </div>
            
                            </div>
                        </div>
                        <div class="mt-5 text-center">
                            <p>Remember It ? <a href="<%= login_path %>" class="font-weight-medium text-primary"> Sign In here</a> </p>
                            
                        </div>

    </div>
</div>