config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  # get 'errors/not_found'
  # get 'errors/internal_server_error'
  
  resources :microposts
  resources :users do
    member do
      get :following, :followers
    end
  end 
  resources :relationships, only: [:create, :destroy] 
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get "/" => "microposts#index"
  get "sign_up" => "register#new"
  post "sign_up" => "register#create"

  get '/login',to: 'sessions#new'
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"


  match "/404", to: 'errors#not_found', via: :all
  match "/422", to: 'errors#unprocessable', via: :all
  match "/500", to: 'errors#internal_server_error', via: :all
  
  root 'users#index'
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
   
    attr_accessor :remember_token, :activation_token, :reset_token
    before_create :create_activation_digest
    has_many :microposts,dependent: :destroy
    #có nhiều người theo dõi
    has_many :active_relationships, class_name: "Relationship",
                                    foreign_key: "follower_id",
                                    dependent: :destroy
    #theo dõi nhiều người
    has_many :passive_relationships, class_name: "Relationship",
                                    foreign_key: "followed_id",
                                     dependent: :destroy

    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: true
    has_secure_password

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    #khi client login thanh cong 
    #-> he thong se tao ra 1 cookie de luu thong tin xac thuc nguoi dung
    #Cookie này sẽ tồn tại trên trình duyệt web cho đến khi người dùng đăng xuất hệ thống
    #khi user login thì server sẽ sinh ra session, lưu ở server ( trong memory của ram hoặc 
    #save file, tuỳ). Đồng thời server sẽ set header trên response trả về client,
    # mục đích của header này là lưu cookie ở phía client.
    # Trong cookie sẽ có session_id tương ứng với session ở server. 
    #Nhờ đó mà server biết dc ai thực hiện các request ở lần tiếp theo.
    #nếu user ko check vào remember me thì khi server set header sẽ KHÔNG bao gồm expired date cho cookie.
    #khi browser nhận dc lệnh tạo cookie mà ko có expired date, thì nó hiểu đây là "session cookie" - đặc điểm của loại cookie này là khi user tắt browser thì nó xoá cookie này.
    #lúc đó user phải đăng nhập lại.
    #nếu user check vào remember me thì server khi set header SẼ BAO GỒM expired date ( vd 1 năm sau) thi khi user tắt browser cookie này vẫn còn.
    #khi cookie còn hạn thì user còn đăng nhập hoài.
    
    #tao ra 1 mã ngẫu nhiên làm mã thông báo
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    #gán mã(dạng băm) vào [remember_digest] database cho user
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

     # kiểm tra xem [remember_token] của phiên làm việc hiện tại
     # có giống với [remember_digest] đã lưu hay khong. nếu đúng thì đăng nhập thành công
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

    #XÁC THỰC NGƯỜI DÙNG LOGIC
    # sau khi người dùng tạo tại khoản -> hệ thống sẽ tự tạo ra 1 mã xác thực
    def create_activation_digest
        self.activation_token = User.new_token
        self.activation_digest = User.digest(activation_token)
    end

    # Activates an account.
    def activate
        update_attribute(:activated,true)
        update_attribute(:activated_at, Time.zone.now)
    end

    # Sends activation email.
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end


    #KHÔI PHỤC MẬT KHẨU
    #sau khi người dùng dử  dụng quên mật khẩu & nhập email yêu cầu cấp lại mật khẩu
    #bước 1: tạo ra mã resetpassword -> lưu vào database
    def create_reset_digest
        self.reset_token = User.new_token   #gán reset_token = User.new_token ()
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end
    #bươc 2 : gửi mail cho người dùng
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end
    # cấu hình thoi gian 
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end


    # Follows a user.
    def follow(other_user)
        following << other_user
    end

    # Unfollows a user.
    def unfollow(other_user)
        following.delete(other_user)
    end 

    # Returns true if the current user is following the other user.
    def following?(other_user)
        following.include?(other_user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :logged_in_user, only: [:edit, :update, :index, :show]
  before_action :correct_user, only: [:edit, :update]
  before_action :isAdmin, only: [:destroy]

  # GET /users or /users.json
  def index
   
    @users = User.paginate(page: params[:page])
    
  end

  # GET /users/1 or /users/1.json
  def show
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: "User was successfully created." }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
    
    #call back kiểm tra xem đã đăng nhập hay chưa
    def logged_in_user
      unless !!current_user.present?
        store_location
        flash[:notice] = "Please log in."
        redirect_to login_url
        end
    end
    #function trả về  user tránh việc phải gọi truy xuất db nhiều lần
    def correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to(root_url) 
        flash[:alert] = "Bạn không có quyền này."
      end
    end
    def isAdmin
      unless current_user.role?
        redirect_to(root_url) 
        flash[:notice] = "Bạn không có quyền xóa! Bạn không phải admin."
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
 <button class="btn btn btn-sm btn-primary follow" data-follow-id = "<%= @user.id%>" >Follow</button>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="outer w-50 m-auto p-5 ">
    <div class="outer">
        <div class="form-group row mb-4">
            <label for="taskname" class="col-form-label col-lg-2">Name</label>
            <div class="col-lg-10">
                <%= form.text_field :name, placeholder: 'Nhập UserName...' ,class: 'form-control title_category'  %>
            </div>
        </div>
      
        <div class="form-group row mb-4">
            <label for="taskbudget" class="col-form-label col-lg-2">Email</label>
            <div class="col-lg-10">
                <%= form.text_field :email ,placeholder: 'Nhập Email...' ,class: 'form-control peralink_category'  %>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-10 d-flex justify-content-center">
                <button type="submit" class="btn btn-primary new-post mx-2">Submit</button>
                <%= link_to "Hủy", users_path , class: "btn btn-secondary mx-2" %>
                
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/users/_list_users.html.erb
 <% @users.each do |user| %>
      <tr>
        <td>
             <a href="<%= user_path(user) %>" class="mr-3 text-primary" ><%= user.name %></a>
        </td>
        <td><%= user.email %></td>
        <td class="d-flex">
             <a href="<%= user_path(user) %>" class="mr-3 text-primary" data-toggle="tooltip"
                data-original-title="Review"><i class="fas fa-eye font-size-18"></i></a>
   
               <a href="<%= edit_user_path(user) %>" class="mr-3 text-primary" data-toggle="tooltip">
                <i class="fas fa-user-edit font-size-18"></i>
            </a>
            <% if current_user.role? && !(user == current_user) %>
               <%= button_to user_path(user), method: :delete, data: { "toggle" => "tooltip","original-title" => "Delete" }, :onclick => "return confirm('Bạn có muốn xóa không ?')", class: "text-danger delete mr-3 btn btn-link p-0"  do %>
                    <i class="fas fa-trash-alt font-size-18"></i>
               <% end %> 
            <% end %>
            <% if user.activated? %>
               <p style="color:green" data-toggle="tooltip" data-placement="top" title="Account activated!"><i class="fas fa-check-circle"></i></p>
            <% else %>
                <p style="color:gray" data-toggle="tooltip" data-placement="top" title="Account NOT activated! "><i class="fas fa-check-circle"></i></p>
            <% end %>
         </td>
      </tr>
<% end %>
<%= will_paginate @users %>

app/views/users/_profile.html.erb
 <div class="d-flex align-items-center">
                <div class="image"> <img src="https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80" class="rounded" width="155"> </div>
                <div class="ml-3 w-100">
                    <h4 class="mb-0 mt-0"> <%= @user.name %></h4> 
                    <span> <%= @user.email %></span>
                    <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                    
                        <div class="d-flex flex-column text-center"> <span class="articles p-3">Bài viết</span> <span class="number1"> <%= @user.microposts.count %></span> </div>
                        <div class="d-flex flex-column text-center"> <span class="followers p-3">Người theo dõi</span> <span class="number2"><%=@user.followers.count %></span> </div>
                        <div class="d-flex flex-column text-center"> <span class="followers p-3">Đang theo dõi</span> <span class="number2"><%=@user.following.count %></span> </div>
                    </div>
                    <% if current_user.present? %>
                              <div class="button mt-2 d-flex flex-row align-items-center">
                                    
                                    <% unless current_user?(@user) %>
                                    <button class="btn btn-sm btn-outline-primary w-75 mr-3">Chat</button>
                                        <div id="follow_form">
                                            <% if current_user.following?(@user) %>
                                                <%= render 'users/unfollow' %>
                                            <% else %>
                                                <%= render 'users/follow' %>
                                            <% end %>
                                        </div>
                                    <% end %> 
                                </div>
                    <% end %>
                  
                </div>
            </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
    html: { method: :delete }, remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn btn-sm btn-outline-danger" %>
<% end %>

app/views/users/create.js.erb
$("#users").html("<%= escape_javascript(render('users/list_users')) %>");

app/views/users/edit.html.erb
<h1 class="text-center">Chỉnh sửa thông tin Thành Viên</h1>

<%= render 'form', user: @user %>
<div class="d-flex justify-content-around ">
    <%= link_to 'Xem Chi Tiết', @user , class: "btn btn-info mx-2" %> 
    <%= link_to 'Quay lại', users_path , class: "btn btn-primary mx-2"%>
</div>

app/views/users/index.html.erb
<div class="row">
    <div class="col-12">
     
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">Thành Viên (<%= @users.count %>)</h4>

            <div class="page-title-right">
                <a href="<%= sign_up_path %>"
                    class="btn btn-success  mb-2 mr-2 rounded-pill"><i
                        class="fas fa-user-plus mr-1"></i>Đăng ký tài khoản</a>
            </div>

        </div>
    </div>
</div>
<p id="notice"><%= notice %></p>
<p id="alert" style="color:red"><%= alert %></p>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <table id="datatable" class="table table-bordered dt-responsive nowrap"
                style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Hành động</th>
                        </tr>
                    </thead>
                    <tbody >
                        <%= render partial: 'list_users'%>
                    </tbody>
                </table>

            </div>
        </div>

    </div> <!-- end col -->
</div> <!-- end row -->

app/views/users/new.html.erb
<h1 class="text-center">Thêm Thành Viên</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class ="profile_user">
    <div class="container my-3 d-flex justify-content-center">
        <div class="card p-3" id= "profile-user">
                <%= render partial: "profile" %>
        </div>
    </div>
</div>


<div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    
                    <div class="crypto-buy-sell-nav">
                        <ul class="nav nav-tabs nav-tabs-custom" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link " data-toggle="tab" href="#list_post" role="tab">
                                    Bài viết (<%= @user.microposts.count%>)
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#follows" role="tab">
                                    Người theo dõi (<%= @user.followers.count%>)
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#followeds" role="tab">
                                    Đang theo dõi (<%= @user.following.count%>)
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#1" role="tab">
                                    Chủ đề 
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#2" role="tab">
                                    Tag
                                </a>
                            </li>
                        </ul>

                        <div class="tab-content crypto-buy-sell-nav-content">
                            <div class="tab-pane active" id="list_post" role="tabpanel">
                    
                                <!-- post item here -->
                                    <%= render partial: 'microposts/list_microposts' , locals: {user: @user}%>
                            </div>

                            <div class="tab-pane" id="follows" role="tabpanel">
                                <div class="row">
                                     <% @user.followers.each do |user| %>
                                        <div class="card m-3" style="width: 19rem;">
                                            <div class="card-body">
                                                <div class="d-flex justify-content-between py-2 align-items-center">
                                                        <a href="<%= user_path(user) %>" class="mr-3 text-primary" ><h5><%= user.name %></h5></a>
                                                          <%
=begin%>
 <% if current_user.present? && current_user.following_ids.include?(user.id)%>
                                                                    <%= button_to  relationship_path(current_user.active_relationships.find_by(followed_id: user.id).id), method: :delete, class: "btn btn-outline-primary btn-sm btn-follow" do%>
                                                                            Hủy theo dõi
                                                                    <% end  %>
                                                            <% else %>
                                                                    <% if user != current_user%>
                                                                          <button class="btn btn btn-sm btn-primary follow" data-follow-id = "<%= user.id%>" >Follow</button>
                                                                    <% end %>
                                                                   
                                                         <% end %> 
<%
=end%>
                                                </div>
                                                
                                                <h6 class="card-subtitle mb-2 text-muted"><%= user.email %></h6>
                                                <div class="d-flex justify-content-between py-2 align-items-center">
                                                        <span>
                                                            <h6 class="card-title mb-0">Post</h6>
                                                            <p><%= user.microposts.count %></p>
                                                        </span>
                                                        <span>
                                                            <h6 class="card-title mb-0">Follower</h6>
                                                            <p><%= user.followers.count %></p>
                                                        </span>
                                                </div>
                                                
                                                
                                               
                                            </div>
                                            </div>
                                    <% end %>
                                </div>
                            </div>
                            <div class="tab-pane" id="followeds" role="tabpanel">
                                <div class="row">
                                    <% @user.following.each do |user| %>
                                        <div class="card m-3" style="width: 19rem;">
                                            <div class="card-body">
                                                <div class="d-flex justify-content-between py-2 align-items-center">
                                                      <a href="<%= user_path(user) %>" class="mr-3 text-primary" ><h5><%= user.name %></h5></a>
                                                          <%
=begin%>
 <% if current_user.present? && current_user.following_ids.include?(user.id)%>
                                                                    <%= button_to  relationship_path(current_user.active_relationships.find_by(followed_id: user.id).id), method: :delete, class: "btn btn-outline-primary btn-sm btn-follow" do%>
                                                                            Hủy theo dõi
                                                                    <% end  %>
                                                            <% else %>
                                                                    <% if user != current_user%>
                                                                         <%= form_for(current_user.active_relationships.build) do |f| %>
                                                                            <div><%= hidden_field_tag :followed_id, @user.id %></div>
                                                                            <%= f.submit "Follow", class: "btn btn btn-sm btn-primary" %>
                                                                         <% end %>
                                                                    <% end %>
                                                                   
                                                         <% end %> 
<%
=end%>
                                                </div>
                                                
                                                <h6 class="card-subtitle mb-2 text-muted"><%= user.email %></h6>
                                                <div class="d-flex justify-content-between py-2 align-items-center">
                                                        <span>
                                                            <h6 class="card-title mb-0">Post</h6>
                                                            <p><%= user.microposts.count %></p>
                                                        </span>
                                                        <span>
                                                            <h6 class="card-title mb-0">Follower</h6>
                                                            <p><%= user.followers.count %></p>
                                                        </span>
                                                </div>
                                                
                                                
                                               
                                            </div>
                                            </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>