config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  # get 'errors/not_found'
  # get 'errors/internal_server_error'
  
  resources :microposts
  resources :users do
    member do
      get :following, :followers
    end
  end 
  resources :relationships, only: [:create, :destroy] 
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get "/" => "microposts#index"
  get "sign_up" => "register#new"
  post "sign_up" => "register#create"

  get '/login',to: 'sessions#new'
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"


  match "/404", to: 'errors#not_found', via: :all
  match "/422", to: 'errors#unprocessable', via: :all
  match "/500", to: 'errors#internal_server_error', via: :all
  
  root 'users#index'
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
            <% if current_user.present? %>  
                <a class="nav-link" href="<%=  user_path(current_user.id)  %>">Profile</a>
            <% end %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= users_path %>">Member</a>
      </li>
      
    </ul>
    <% if current_user.present? %>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <%= current_user.name  %>
          </a>
          <div class="dropdown-menu w-50 m-auto" aria-labelledby="navbarDropdownMenuLink">

            <a class="dropdown-item" href="#">Seting</a>
           
            <%= button_to  logout_path, method: :delete,class: "dropdown-item text-danger" do%>
                                      Logout
            <% end  %>
          </div>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav">
          <li class="nav-item ">
            <a class="nav-link " href="<%= login_path %>"  >
              Sign Up | Sign In
            </a>
          </li>

      </ul>
    <% end %>
  </div>
</nav>