config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  # get 'errors/not_found'
  # get 'errors/internal_server_error'
  
  resources :microposts
  resources :users do
    member do
      get :following, :followers
    end
  end 
  resources :relationships, only: [:create, :destroy] 
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get "/" => "microposts#index"
  get "sign_up" => "register#new"
  post "sign_up" => "register#create"

  get '/login',to: 'sessions#new'
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"


  match "/404", to: 'errors#not_found', via: :all
  match "/422", to: 'errors#unprocessable', via: :all
  match "/500", to: 'errors#internal_server_error', via: :all
  
  root 'users#index'
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    validates :content, length: { maximum: 140 }, presence: true
    validates :user_id, presence: true
   
  
  # Returns a resized image for display.
    def display_image
         image.variant(resize_to_limit: [500, 500])
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  include SessionsHelper
  before_action :set_micropost, only: %i[ show edit update destroy ]
  before_action :logged_in_user, only: [:create, :destroy, :index]
  before_action :correct_user, only: :destroy
  # GET /microposts or /microposts.json
  def index
    @microposts = Micropost.page(params[:page]).per(10)
  end

  # GET /microposts/1 or /microposts/1.json
  def show
    @posts = Micropost.all.order(created_at: :desc)
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    respond_to do |format|
      if @micropost.save
        format.html { redirect_to microposts_path, notice: "Micropost was successfully created." }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: "Micropost was successfully updated." }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:content, :title, :image)
    end
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
    def logged_in_user
      unless !!current_user.present?
        store_location
        flash[:notice] = "Please log in."
        redirect_to login_url
        end
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
   <div class="outer">
      <div class="outer">
          <div class="form-group row mb-4">
              <label for="taskname" class="col-form-label col-lg-2">Tiêu đề</label>
              <div class="col-lg-10">
                  <%= form.text_field :title, placeholder: 'Tiêu đề bài viết là gì ...' ,class: 'form-control'  %>
              </div>
          </div>
          
          <div class="form-group row mb-4">
              <label class="col-form-label col-lg-2">Nội dung</label>
              <div class="col-lg-10">
                  <div class="">Bạn đang nghĩ gì ?</div>
                  <%= form.text_area :content, class: "form-control content_post" %>
              </div>
          </div>
      
      </div>
    </div>
    <div class="text-center">
        <%= link_to "Hủy", root_path , class: "btn btn-info mx-2" %>
        <%= form.submit "Post", class: "btn btn-primary" %>
    </div>                         
    <span class="image">
        <%= form.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
    </span>
<% end %>

                                        
                                                         
                                    

app/views/microposts/_list_microposts.html.erb
                                        <% @user.microposts.each do |post| %>
                                                <div class="post-item shadow my-3">
                                                    <div class="item-head d-flex align-item-center">
                                                        <div class="author-avatar bg-white p-1 rounded">
                                                                        <!-- avatar of user here -->       
                                                        </div>
                                                        <div class="post-meta ml-2 flex-grow-1 py-2">
                                                            <div class="d-flex align-items-center justify-content-between">
                                                                <div class="post-detal">
                                                                    <div class="author-info pb-2 position-relative">
                                                                                <div class="user-name d-flex align-items-center">
                                                                                    <a href="#" class="show-info-user"  data-id-user="<%= post.user.id %> " ><h5 class="mb-0"><%= post.user.name %> </h5></a>
                                                                                    <span class="mx-2">-</span>
                                                                                    <p class="mb-0 d-inline-block"><%= time_ago_in_words(post.created_at) %> ago</p>
                                                                                    
                                                                                </div> 
                                                                        </div>
                                                                        <div>
                                                                            <p class="d-inline mb-0">
                                                                                <a href="<%= micropost_path(post) %>" class="text-dark text-capitalize">
                                                                                    <%= post.title %>
                                                                                </a>
                                                                            </p>
                                                                            
                                                                        </div>
                                                                        
                                                                        </div>
                                                                      <div class="option_post d-flex align-items-center">
                                                                            <% if @user == current_user && @user.activated? %>
                                                                                <a href="<%= edit_micropost_path(post) %>" class="mr-3 text-primary" data-toggle="tooltip">
                                                                                    <i class="fas fa-edit font-size-18"></i>
                                                                                </a>
                                                                                <a href="<%= micropost_path(post)%>" target="_blank" class="mr-3 text-primary" data-toggle="tooltip">
                                                                                        <i class="fas fa-eye font-size-18"></i>
                                                                                </a>
                                                                                <%= button_to micropost_path(post), method: :delete, data: { "toggle" => "tooltip","original-title" => "Delete" }, :onclick => "return confirm('Bạn có muốn xóa không ?')", class: "text-danger delete mr-3 btn btn-link p-0"  do %>
                                                                                    <i class="fas fa-trash-alt font-size-18"></i>
                                                                                <% end %>
                                                                            <% else %>
                                                                                    <a href="<%= micropost_path(post)%>" target="_blank" class="mr-3 text-primary" data-toggle="tooltip">
                                                                                        <i class="fas fa-eye font-size-18"></i>
                                                                                    </a>
                                                                            <% end %>
                                                                    </div>
                                                            </div>
                                                          
                                                        </div>
                                                    </div>
                                                    

                                                </div>
                                            <% end %>

app/views/microposts/destroy.js.erb
$('#list_post').html('<%= escape_javascript(render partial: 'microposts/list_microposts') %>')

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-12">
     
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">Tất cả bài viết(<%= Micropost.count %>)</h4>

            <div class="page-title-right">
                <a href="<%= new_micropost_path %>"
                    class="btn btn-success  mb-2 mr-2 rounded-pill"><i
                        class="fas fa-user-plus mr-1"></i>Bài viết mới</a>
            </div>

        </div>
    </div>
</div>
<% @microposts.each do |post| %>
    <div class="post-item shadow my-3">
        <div class="item-head d-flex align-item-center">
            <div class="author-avatar bg-white p-1 rounded">
                            <!-- avatar of user here -->       
            </div>
            <div class="post-meta ml-2 flex-grow-1 py-2">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="post-detal">
                        <div class="author-info pb-2 position-relative">
                                    <div class="user-name">
                                         <a href="<%= micropost_path(post) %>" class="text-dark text-capitalize">
                                             <h5 style="color:blue"> <%= post.title %> </h5>
                                         </a>
                                        <span class="d-flex align-items-center py-2">Tác giả : <a href="<%= user_path(post.user) %>" class="mr-3 text-primary" ><h5 class="mb-0"><%= post.user.name %></h5></a> </span>
                                        <span>Ngày đăng : <%= post.created_at %></span>
                                        <hr>
                                    </div> 
                            </div>
                            <div>
                               
                               
                            </div>
                            
                            </div>
                       
                </div>
              
            </div>
        </div>
        

    </div>
<% end %>
<%= paginate @microposts, theme: 'twitter-bootstrap-4',
        pagination_class: "pagination justify-content-center",
        nav_class: "d-inline-b page-paginate"  %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row px-5">
  <div class="col-12 col-lg-8">
      <div class="content-post ">
            <div class="content">
                <div class="container">
                  <h2><%= @micropost.title %></h2>
                   
                  <span class="d-flex align-items-center py-2">Tác giả : <a href="<%= user_path(@micropost.user) %>" class="mr-3 text-primary" ><h5 class="mb-0"><%= @micropost.user.name %></h5></a> </span>
                  <span>Ngày đăng : <%=@micropost.created_at %></span>
                  <hr>
                  <p><%= @micropost.content %></p>
                  <%= image_tag @micropost.image , class: "post_image_conver w-100" if @micropost.image.attached? %>
                </div>
            </div>
            <p class="text-center my-5">[HẾT]</p>
            <hr>
      </div>
      <h5>Xem thêm bài viết từ <%= @micropost.user.name %></h5>
       <div class="row">
                <% @micropost.user.microposts.limit(3).each do |post| %>
                    <div class="card m-2" style="width: 17rem;">
                        <div class="card-body">
                            <div>
                                <h5><%= post.title %></h5>
                            </div>
                             <p class="mb-0 d-inline-block"><%= time_ago_in_words(post.created_at) %> ago</p>
                            <div class="d-flex justify-content-between py-2 align-items-center">
                                  <h6><%= post.user.name %></h6>

                            </div>
                            
                        </div>
                        </div>
                <% end %>
            </div>
  </div>
  <div class="col-lg-4 col-12">
    <div class="newest-post">
        <h4>Bài viết mới</h4>
        <hr>
         <%  @posts.each do |post| %>
                    <div>
                        <h5><%= post.title %></h5>
                    </div>
                      <p class="mb-0 d-inline-block"><%= time_ago_in_words(post.created_at) %> ago</p>
                    <div class="d-flex justify-content-between py-2 align-items-center">
                          <h6><%= post.user.name %></h6>
                  </div>
                  <hr>
        <% end %>
    </div>
  </div>
</div>